# Generated by Django 5.1.3 on 2024-11-09 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('mgbytes', models.CharField(max_length=4, verbose_name='Megabytes')),
                ('price', models.FloatField(verbose_name='Precio')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, verbose_name='Direccion')),
                ('coordinates', models.CharField(max_length=200, verbose_name='Cordenadas Ubicacion')),
                ('url_gps', models.URLField(verbose_name='Url Gps ')),
                ('box', models.CharField(max_length=200, verbose_name='Coordenadas Caja')),
                ('ont', models.CharField(max_length=200, verbose_name='Sn Ont')),
                ('router', models.CharField(max_length=200, verbose_name='Sn Router')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status Activo ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contract.plan')),
            ],
        ),
    ]
