# Generated by Django 5.1.3 on 2024-11-25 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_alter_contract_address_alter_contract_box_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='mgbytes',
            new_name='megabytes',
        ),
        migrations.AlterField(
            model_name='contract',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.plan'),
        ),
    ]
