# Generated by Django 5.1.3 on 2024-11-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
