# Generated by Django 5.1.3 on 2024-11-13 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0002_rename_customer_contract_customer'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_attentions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.TimeField(verbose_name='Hora de entrada')),
                ('final_time', models.TimeField(verbose_name='Hora de salida')),
                ('diagnostic', models.TextField(max_length=300, verbose_name='Diagnostico diagnostico')),
                ('pot_final', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Potencia final')),
                ('action_corrective', models.TextField(max_length=100, verbose_name='Diagnostico del problema')),
                ('remote_managment', models.BooleanField(default=False, verbose_name='Accesso remoto')),
                ('aditional_note', models.TextField(max_length=1000, null=True, verbose_name='Nota adicional')),
                ('soluttion_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Pendiente'), (1, 'En progreso'), (2, 'Completo')], default=0)),
                ('assigned_date', models.DateField(verbose_name='Fecha preferencial')),
                ('preferential_time', models.TimeField(verbose_name='Hora preferencial')),
                ('description', models.TextField(max_length=300, verbose_name='Description del problema')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Responsable', to='contract.contract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.profile')),
                ('order_attetions', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.order_attentions', verbose_name='Orden de solucion ')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.type')),
            ],
        ),
    ]
